# <!-- 
# There is an application that needs to be deployed on Kubernetes cluster under Apache web server. The Nautilus application development team has asked the DevOps team to deploy it. We need to develop a template as per requirements mentioned below:


# Create a namespace named as httpd-namespace-devops.

# Create a deployment named as httpd-deployment-devops under newly created namespace. For the deployment use httpd image with latest tag only and remember to mention the tag i.e httpd:latest, and make sure replica counts are 2.

# Create a service named as httpd-service-devops under same namespace to expose the deployment, nodePort should be 30004.

# Note: The kubectl utility on jump_host has been configured to work with the kubernetes cluster.
#  -->



1. kubectl create ns httpd-namespace-devops
2. kubectl config set-context --current --namespace=httpd-namespace-devops



3. vi all.yaml


apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-devops
  template:
    metadata:
      labels:
        app: httpd-devops
    spec:
      containers:
      - name: httpd-devops
        image: httpd:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: httpd-service-devops
spec:
  type: NodePort
  selector:
    app: httpd-devops
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004






