1. kubectl create secret generic media  --from-file=/opt/media.txt




apiVersion: v1
kind: Pod
metadata:
  name: secret-datacenter
  labels:
    name: secret-datacenter
spec:
  containers:
  - name: secret-container-datacenter
    image: fedora:latest
    command: ["/bin/sh","-c","sleep 48000"]
    volumeMounts:
      - name: secret-volume
        mountPath: /opt/demo
  volumes:
    - name: secret-volume
      secret:
        secretName: media


3. kubectl exec -it secret-datacenter -- cat /opt/demo/media.txt

